#!/bin/bash

# author:	Sean O'Beirne
# file:		create-chatgpt-prompt

# usage: create-chatgpt-prompt 

# a prompt to give ChatGPT to template a compatible test

################################################################################
